### ISSUE TITLE
Index Error. Why is it empy?

### ISSUE THREAD

**Issue by dover247** [dover247/PTGuru-Bot#7]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "PTGuruBot.py", line 38, in on_ready
    await update_all_feeds()
  File "PTGuruBot.py", line 43, in update_all_feeds
    await post_feeds(cve_feed, vulnerability_channel)
  File "PTGuruBot.py", line 57, in post_feeds
    await feed_procedure(feeder, channel)
  File "PTGuruBot.py", line 61, in feed_procedure
    entry = feeder.entries[0]
IndexError: list index out of range

**Comment by dover247** [comment]
FIX:
try:
        feeder = feedparser.parse(feed)
        await feed_procedure(feeder, channel)
    except IndexError:
        for feed_source in feed:
            feeder = feedparser.parse(feed_source)
            await feed_procedure(feeder, channel)
